name: railway_station_finder
description: "LOCO - AI-Powered Intelligent Urban Rail Mobility Platform for Mumbai."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  geolocator: ^11.0.0
  s2geometry: ^0.2.1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.3
  pin_code_fields: ^8.0.1
  sqflite: ^2.4.4
  path: ^1.9.1
  local_auth: ^3.0.2
  crypto: ^3.0.7
  sqflite_common_ffi: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/default_stations.json
    - assets/loco_logo.png
    - assets/mumbai_live_rail_feed.json
    - assets/crowd_ml_model.json
