name: railway_station_finder
description: A Flutter application to find the nearest railway station using S2 Geometry.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  geolocator: ^11.0.0
  s2geometry: ^0.2.1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.3
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/default_stations.json
